name: "CI"
on:
  pull_request:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2.3.4
    - name: Install nix
      uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: ryantm-test
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build shell.nix -A inputDerivation
    - run: nix-shell --run "cowsay OK"
